// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByAyz9FwIML4bLNBzZHmWSvc07UWjYCCY',
    appId: '1:650154785565:web:16bc8327b142c61abcfff4',
    messagingSenderId: '650154785565',
    projectId: 'fir-565a9',
    authDomain: 'fir-565a9.firebaseapp.com',
    storageBucket: 'fir-565a9.appspot.com',
    measurementId: 'G-BK84879D5N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhA-vFMA6FCkaI0gsJzeigSsu7odO77pY',
    appId: '1:650154785565:android:908fcc386f471270bcfff4',
    messagingSenderId: '650154785565',
    projectId: 'fir-565a9',
    storageBucket: 'fir-565a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiS8veOJI_W_f3H8KVvIrQHDjwM0JW9q4',
    appId: '1:650154785565:ios:a4c48a6b659ca8f3bcfff4',
    messagingSenderId: '650154785565',
    projectId: 'fir-565a9',
    storageBucket: 'fir-565a9.appspot.com',
    iosClientId: '650154785565-76l94gat25cggqoiq10dkcn3p7ldc4hi.apps.googleusercontent.com',
    iosBundleId: 'com.example.authBloc',
  );
}
